---
name: action-jira-update-cmr-issue-status

description: Update CMR Issue Status To In Progress

inputs:
  ticket-id:
    description: Ticket ID
    required: true

outputs:
  ticket-exists:
    description: Whether the ticket exists or not on the Jira instance
    value: ${{ steps.update-cmr-status.outputs.exists }}
  project-id:
    description: Denotes the project id of which the ticket is part of
    value: ${{ steps.update-cmr-status.outputs.project-id}}


runs:
  using: composite
  steps:

    - uses: atlassian/gajira-login@45fd029b9f1d6d8926c6f04175aa80c0e42c9026  # Logs In To JIRA
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-username }}
        JIRA_API_TOKEN: ${{ inputs.jira-token }}

    - name: Update CMR Ticket Status
      id: update-cmr-status
      shell: bash
      env:
        JIRA_USER_EMAIL: ${{inputs.jira-username}}
        JIRA_API_TOKEN: ${{inputs.jira-token}}
        JIRA_BASE_URL: ${{inputs.jira-base-url}}
      run: ${{github.action_path}}/../scripts/update-status.sh "$TICKET_ID"
    