name: jira-cm-ticket

description: Deployment Pipeline Gate Based On CM Ticket Status

inputs:
  ticket-id:
    description: Ticket ID
    required: true
  jira-api-token:
    description: JIRA API Token
    required: true
  jira-base-url:
    description: JIRA Base URL
    required: false
    default: https://wbdstreaming.atlassian.net/
  jira-api-username:
    description: JIRA API Username
    required: true
  is-rollback:
    description: Flag to denote if the deployment is a Rollback
    required: true
    type: boolean

outputs:
  ticket-exists:
    description: If Ticket Exists
    value: ${{steps.check-ticket.outputs.exists}}

runs:
  using: composite
  steps:

    # Fail Close If Credentials Not Found
    - uses: atlassian/gajira-login@45fd029b9f1d6d8926c6f04175aa80c0e42c9026  # Logs In To JIRA
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-api-username }}
        JIRA_API_TOKEN: ${{ inputs.jira-api-token }}

    - uses: atlassian/gajira-cli@ec286a2b00ebe4cde39f12d888f641411d446723 # Installs JIRA CLI
      with:
        version: 1.0.27

    # Fail Close If CM Ticket Not Found
    - name: Check If Ticket Exists
      id: check-ticket
      shell: bash
      env:
        JIRA_USER_EMAIL: ${{inputs.jira-api-username}}
        JIRA_API_TOKEN: ${{inputs.jira-api-token}}
        JIRA_BASE_URL: ${{inputs.jira-base-url}}
        TICKET_ID: ${{inputs.ticket-id}}
      run: ${{github.action_path}}/../scripts/check-cm-ticket.sh "$TICKET_ID"

    # Conditionally Update CM Ticket Status To In Progress
    - name: Update CM Ticket Status To In Progress
      id: update-status
      if: ${{ inputs.is-rollback == 'false' }}
      shell: bash
      env:
        JIRA_USER_EMAIL: ${{inputs.jira-api-username}}
        JIRA_API_TOKEN: ${{inputs.jira-api-token}}
        JIRA_BASE_URL: ${{inputs.jira-base-url}}
        IS_ROLLBACK: ${{ inputs.is-rollback }}
      run: |
        ${{ github.action_path }}/../scripts/update-cm-ticket.sh "$TICKET_ID" "$IS_ROLLBACK"
    
    # Calculate Current UTC Time and Format Comment
    - name: Calculate Current UTC Time and Format Comment
      id: format-comment
      shell: bash
      run: |
        CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        if [ "${{ inputs.is-rollback }}" == "true" ]; then
          FORMATTED_COMMENT="${{ github.actor }} triggered rollback at $CURRENT_TIME with the following parameters ..."
        else
          FORMATTED_COMMENT="${{ github.actor }} triggered release cadence at $CURRENT_TIME with the following parameters ..."
        fi
        echo "FORMATTED_COMMENT=$FORMATTED_COMMENT" >> $GITHUB_ENV

    - name: Comment on JIRA Ticket
      uses: ./comment
      with:
        ticket-id: ${{ inputs.ticket-id }}
        comment: ${{ env.FORMATTED_COMMENT }}
        jira-username: ${{ inputs.jira-api-username }}
        jira-token: ${{ inputs.jira-api-token }}
        jira-base-url: ${{ inputs.jira-base-url }}