name: Test JIRA Status Change Action

on:
  workflow_dispatch:
    inputs:
      ticket-id:
        description: "Ticket ID"
        required: true
        default: "KAN-1"


jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Variables for workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "TICKET_ID=${{ github.event.inputs.ticket-id }}" >> $GITHUB_ENV

      # - name: Set Variables for push
      #   if: ${{ github.event_name == 'push' }}
      #   run: |
      #     echo "TICKET_ID=KAN-1" >> $GITHUB_ENV

      - name: Make the script executable
        run: chmod +x ./scripts/change-status.sh

      - name: Run JIRA Status Change Action
        id: jira-status-change
        uses: ./change-status
        with:
          ticket-id: ${{ env.TICKET_ID }}
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}

      - name: Check Ticket Exists Output
        run: |
          echo "Ticket exists: ${{ steps.jira-status-change.outputs.ticket-exists }}"
