name: action-jira-change-issue-status

description: Change Issue Status

inputs:
  ticket-id:
    description: Ticket ID
    required: true
  jira-username:
    description: Username Of JIRA Account
    required: true
  jira-token:
    description: API Token
    required: true
  jira-base-url:
    description: Base URL Of JIRA Instance
    required: true

outputs:
  ticket-exists:
    description: If Ticket Exists
    value: ${{steps.check-ticket.outputs.exists}}

runs:
  using: composite
  steps:

    - uses: atlassian/gajira-login@45fd029b9f1d6d8926c6f04175aa80c0e42c9026  # Logs In To JIRA
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-username }}
        JIRA_API_TOKEN: ${{ inputs.jira-token }}

    - uses: atlassian/gajira-cli@ec286a2b00ebe4cde39f12d888f641411d446723 # Installs JIRA CLI
      with:
        version: 1.0.27

    - name: Check If Ticket Exists
      id: check-ticket
      shell: bash
      env:
        JIRA_USER_EMAIL: ${{inputs.jira-username}}
        JIRA_API_TOKEN: ${{inputs.jira-token}}
        JIRA_BASE_URL: ${{inputs.jira-base-url}}
        TICKET_ID: ${{inputs.ticket-id}}
      run: ${{github.action_path}}/../scripts/change-status.sh "$TICKET_ID"
    
    - name: Change Status Of JIRA Ticket
      if: steps.check-ticket.outputs.exists == 'true'
      shell: bash
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_API_TOKEN: ${{ inputs.jira-token }}
        TICKET_ID: ${{ inputs.ticket-id }}
      run: ${{github.action_path}}/../scripts/change-status.sh "$TICKET_ID"

    